version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    #environment:
       #MONGO_INITDB_ROOT_USERNAME: max
       #MONGO_INITDB_ROOT_PASSWORD: secret
      #or
      #- MONGO_INITDB_ROOT_USERNAME=max
    #or
    env_file:
        - ./env/mongo.env
  backend:
    build: ./backend
    #docker compose will look in the folder backend to get the Dockerfile the run it to build our image, then the image will be used in the actual container 
    #OR
    #build: 
    # context: ./backend
    # dockerfile: DockerfilName
    # args:
    #     some-args
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules 
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

  #frontend:

##Name volume, only for named volume
volumes:
  data:
  logs: